version: '3.8'
services:
  db:
     image: mysql:latest
     environment:
      MYSQL_ROOT_PASSWORD: vicky
      MYSQL_DATABASE: weather
     ports:
      - "3308:3306"
     healthcheck:
      test: ["CMD","mysqladmin","ping","--silent"]
      interval: 30s
      timeout: 10s
      retries: 5
  app:
   build: .
   depends_on:
    db : 
     condition: service_healthy
   ports:
    - "8080:8080"
    
   environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/weather
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: vicky
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect